trigger: none
# schedules:
# - cron: "0 16 * * 1-5"  # At 16:00 UTC on every day-of-week from Monday through Friday
  # displayName: Daily Cleanup
  # branches:
  #   include:
  #   # - main # Uncomment for running on main branch
  #   - feature/4075-knowledge-management
  # always: true
jobs:
- job: Cleanup
  steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'VSE AI Assistent DEV'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          SUBSCRIPTION_ID='6ed9935b-8a0e-4136-a032-4921ae65ef71'
          RESOURCE_GROUP='cloud-shell-storage-westeurope' 
          TENANT_ID=$(az account show --query tenantId -o tsv)
          APP_ID=$(az ad sp list --display-name "policyaiassistant-dev-wa" --query "[0].appId" -o tsv)
          SECRET=$(az ad sp credential reset --name $APP_ID --query password -o tsv)
          RESOURCES=$(az resource list --resource-group $RESOURCE_GROUP --query "[].{Name:name, Type:type}" -o tsv)
          for RESOURCE in $RESOURCES
          do
            RESOURCE_NAME=$(echo $RESOURCE | awk '{print $1}')
            RESOURCE_TYPE=$(echo $RESOURCE | awk '{print $2}')
            RESOURCE_LOCATION=$(az resource show --name $RESOURCE_NAME --resource-group $RESOURCE_GROUP --resource-type $RESOURCE_TYPE --query location -o tsv)
            if [[ "$RESOURCE_TYPE" == "Microsoft.CognitiveServices/accounts" ]]; then
              ACCESS_TOKEN=$(az account get-access-token --query accessToken -o tsv)
              curl -X POST -H "Authorization: Bearer $ACCESS_TOKEN" -H "Content-Type: application/json" https://management.azure.com/subscriptions/$SUBSCRIPTION_ID/providers/Microsoft.CognitiveServices/locations/$RESOURCE_LOCATION/resourceGroups/$RESOURCE_GROUP/deletedAccounts/$RESOURCE_NAME?Api-Version=2021-04-30
            else
              az resource delete --name $RESOURCE_NAME --resource-group $RESOURCE_GROUP --yes
            fi
          done
          az group delete --name $RESOURCE_GROUP --yes --no-wait