trigger: none
pool:
  vmImage: ubuntu-latest
# Use azd provided container image that has azd, infra, multi-language build tools pre-installed.
container: mcr.microsoft.com/azure-dev-cli-apps:latest

steps:
  - pwsh: |
      azd config set auth.useAzCliAuth "true"
    displayName: Configure AZD to Use AZ CLI Authentication.

  - task: AzureCLI@2
    displayName: Deploy Application
    inputs:
      azureSubscription: "Sandbox ARM Service Connection"
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        azd deploy --no-prompt
    env:
      AZURE_SUBSCRIPTION_ID: 6ed9935b-8a0e-4136-a032-4921ae65ef71
      AZURE_ENV_NAME: ai-ass-dev
      AZURE_LOCATION: "West Europe"